const AllData = {
  base_url:"http://180.96.16.167:1855"
}
const PortName = {
  login : "/admin/login",
  login_code :"/admin/login_code",
  menu_list:"/admin/menu",
  book_list:"/book/list",
  collect_list:"/lcollect/list",
  book_type_delete:"/book/deletes",
  collect_delete:"/lcollect/deletes",
  special_list:"/special/list",
  special_delete: "/special/deletes",
  record_list:"/record/list",
  archive_list:"/archive/list",
  record_deletes:"/record/deletes",
  book_timeperiod:"/book/timeperiod",
  book_timeline:"/book/timeline",
  record_timeline:"/record/timeline",
  record_timeperiod:"/record/timeperiod",
  acollect_list:"/acollect/list",
  acollect_deletes:"/acollect/deletes",
  user_list:"/user/list",
  user_deletes:"/user/freezes",
  user_undeletes:"/user/unfreezes",
  admin_list:"/admin/list",
  role_list:"/role/list",
  admin_deletes:"/admin/deletes",
  admin_save:"/admin/save",
  book_get:"/book/get",
  file_upload:"/file/upload",
  book_save:"/book/save",
  file_time:"/file/time",
  lcollect_get:"/lcollect/get",
  lcollect_examine:"/lcollect/examine",
  special_save: "/special/save",
  special_get: "/special/get",
  record_save:"/record/save",
  record_get:"/record/get",
  acollect_get:"/acollect/get",
  acollect_examine:"/acollect/examine",
  admin_get:"/admin/get",
  admin_pending:"/admin/pending",
  file_list:"/file/list",
  file_delete:"/file/delete",
  file_preview:"/file/preview",
  exhibition_list:"/exhibition/list",
  exhibition_save:"/exhibition/save",
  exhibition_get:"/exhibition/get",
  course_list:"/course/list",
  exhibition_deletes:"/exhibition/deletes",
  exhibition_timeline:"/exhibition/timeline",
  exhibition_timeperiod:"/exhibition/timeperiod",
  course_get:"/course/get",
  course_save:"/course/save",
  course_deletes:"/course/deletes",
  lecturer_allList:"/lecturer/allList",
  chapter_get:"/chapter/get",
  video_get:"/video/get",
  chapter_save:"/chapter/save",
  video_save:"/video/save",
  chapter_deletes:"/chapter/deletes",
  video_deletes:"/video/deletes",
  book_publishs:"/book/publishs",
  special_publishs:"/special/publishs",
  record_publishs:"/record/publishs",
  course_publishs:"/course/publishs",
  exhibition_publishs:"/exhibition/publishs",
  admin_retrieve_code:"/admin/retrieve_code",
  admin_retrieve:"/admin/retrieve"
}
const SessionKey = {
  ISLOGGED:"islogged",
  TIME:"time",
  ID:"id",
  MOBILE:"mobile",
  PASSWORD:"password",
  ROLE:"role",
  FIRST:"first",
  SECOND:"second",
  TIMEZ:"timez"

}
export { AllData,PortName,SessionKey }
